theme: jekyll-theme-minimal
title: GH-tfuser titleleiste
description: Das ist die Beschreibung für meine Seite tfuser

#github_username:  tfuser

#markdown:  kramdown
#gems:  - jekyll-feed

#exclude:  - Gemfile
#          - Gemfile.lock
          
